name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add Production JWT Key
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '${{ github.workspace }}/appsettings.Production.json'
        keyname1: 'JwtKey'
        valuetoset: '${{ secrets.JWT_KEY }}'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: mkiesinski/restaurantservice
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
